

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GeneralWindow(object):
    def setupUi(self, GeneralWindow):
        GeneralWindow.setObjectName("GeneralWindow")
        GeneralWindow.resize(650, 300)
        GeneralWindow.setMaximumSize(QtCore.QSize(650, 300))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        GeneralWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/appicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GeneralWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(GeneralWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 111, 111))
        self.groupBox.setObjectName("groupBox")
        self.rdCsv = QtWidgets.QRadioButton(self.groupBox)
        self.rdCsv.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.rdCsv.setObjectName("rdCsv")
        self.rdGui = QtWidgets.QRadioButton(self.groupBox)
        self.rdGui.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.rdGui.setObjectName("rdGui")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 130, 611, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lblOutput = QtWidgets.QLabel(self.groupBox_2)
        self.lblOutput.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.lblOutput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOutput.setObjectName("lblOutput")
        self.txtOutput = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtOutput.setGeometry(QtCore.QRect(70, 30, 531, 20))
        self.txtOutput.setObjectName("txtOutput")
        self.txtCsv = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtCsv.setGeometry(QtCore.QRect(70, 60, 531, 20))
        self.txtCsv.setObjectName("txtCsv")
        self.lblCsv = QtWidgets.QLabel(self.groupBox_2)
        self.lblCsv.setGeometry(QtCore.QRect(30, 60, 31, 20))
        self.lblCsv.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCsv.setObjectName("lblCsv")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(280, 250, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(140, 10, 491, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lblGroupName = QtWidgets.QLabel(self.groupBox_3)
        self.lblGroupName.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lblGroupName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGroupName.setObjectName("lblGroupName")
        self.txtGroupName = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtGroupName.setGeometry(QtCore.QRect(100, 20, 381, 20))
        self.txtGroupName.setObjectName("txtGroupName")
        self.txtGridName = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtGridName.setGeometry(QtCore.QRect(100, 50, 381, 20))
        self.txtGridName.setObjectName("txtGridName")
        self.lblGridName = QtWidgets.QLabel(self.groupBox_3)
        self.lblGridName.setGeometry(QtCore.QRect(20, 50, 71, 20))
        self.lblGridName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGridName.setObjectName("lblGridName")
        self.txtVersionBlock = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtVersionBlock.setGeometry(QtCore.QRect(100, 80, 381, 20))
        self.txtVersionBlock.setObjectName("txtVersionBlock")
        self.lblVersionBlock = QtWidgets.QLabel(self.groupBox_3)
        self.lblVersionBlock.setGeometry(QtCore.QRect(20, 80, 71, 20))
        self.lblVersionBlock.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblVersionBlock.setObjectName("lblVersionBlock")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 240, 241, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.txtSkin = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtSkin.setGeometry(QtCore.QRect(100, 20, 131, 20))
        self.txtSkin.setObjectName("txtSkin")
        self.lblSkin = QtWidgets.QLabel(self.groupBox_4)
        self.lblSkin.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.lblSkin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSkin.setObjectName("lblSkin")
        GeneralWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(GeneralWindow)
        QtCore.QMetaObject.connectSlotsByName(GeneralWindow)

    def retranslateUi(self, GeneralWindow):
        _translate = QtCore.QCoreApplication.translate
        GeneralWindow.setWindowTitle(_translate("GeneralWindow", "General Settings"))
        self.groupBox.setTitle(_translate("GeneralWindow", "Import Type"))
        self.rdCsv.setText(_translate("GeneralWindow", "CSV"))
        self.rdGui.setText(_translate("GeneralWindow", "GUI"))
        self.groupBox_2.setTitle(_translate("GeneralWindow", "Path Settings"))
        self.lblOutput.setText(_translate("GeneralWindow", "Output:"))
        self.lblCsv.setText(_translate("GeneralWindow", "Csv:"))
        self.btnSave.setText(_translate("GeneralWindow", "Save!"))
        self.groupBox_3.setTitle(_translate("GeneralWindow", "Find XML Node By Name"))
        self.lblGroupName.setText(_translate("GeneralWindow", "Group Box:"))
        self.txtGroupName.setToolTip(_translate("GeneralWindow", "Find the groupbox where the algo header has to be displayed"))
        self.txtGridName.setToolTip(_translate("GeneralWindow", "Find the grid where the attrbutes have to be displayed"))
        self.lblGridName.setText(_translate("GeneralWindow", "Grid:"))
        self.txtVersionBlock.setToolTip(_translate("GeneralWindow", "Find the texblock where the version has to be displayed"))
        self.lblVersionBlock.setText(_translate("GeneralWindow", "Text Block:"))
        self.groupBox_4.setTitle(_translate("GeneralWindow", "Other Settings:"))
        self.lblSkin.setText(_translate("GeneralWindow", "Skin Version:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GeneralWindow = QtWidgets.QMainWindow()
    ui = Ui_GeneralWindow()
    ui.setupUi(GeneralWindow)
    GeneralWindow.show()
    sys.exit(app.exec_())

