

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GenerateXAML(object):
    def setupUi(self, GenerateXAML):
        GenerateXAML.setObjectName("GenerateXAML")
        GenerateXAML.resize(1320, 620)
        GenerateXAML.setMaximumSize(QtCore.QSize(1320, 620))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        GenerateXAML.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/appicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GenerateXAML.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(GenerateXAML)
        self.centralwidget.setObjectName("centralwidget")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(650, 540, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.btnGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerate.setGeometry(QtCore.QRect(400, 540, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnGenerate.setFont(font)
        self.btnGenerate.setObjectName("btnGenerate")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 170, 1281, 341))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 1281, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSkin = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSkin.setMaximumSize(QtCore.QSize(250, 20))
        self.lblSkin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSkin.setObjectName("lblSkin")
        self.gridLayout.addWidget(self.lblSkin, 0, 0, 1, 1)
        self.cmbSkins = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cmbSkins.setObjectName("cmbSkins")
        self.gridLayout.addWidget(self.cmbSkins, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(250, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.lblHeader = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblHeader.setMaximumSize(QtCore.QSize(250, 20))
        self.lblHeader.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblHeader.setObjectName("lblHeader")
        self.gridLayout.addWidget(self.lblHeader, 3, 0, 1, 1)
        self.lblSkinName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSkinName.setMaximumSize(QtCore.QSize(200, 20))
        self.lblSkinName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSkinName.setObjectName("lblSkinName")
        self.gridLayout.addWidget(self.lblSkinName, 1, 0, 1, 1)
        self.txtHeader = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtHeader.setObjectName("txtHeader")
        self.gridLayout.addWidget(self.txtHeader, 3, 1, 1, 1)
        self.lblAlgoAttribute = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblAlgoAttribute.setMaximumSize(QtCore.QSize(250, 20))
        self.lblAlgoAttribute.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAlgoAttribute.setObjectName("lblAlgoAttribute")
        self.gridLayout.addWidget(self.lblAlgoAttribute, 2, 0, 1, 1)
        self.txtAlgoAttribute = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtAlgoAttribute.setObjectName("txtAlgoAttribute")
        self.gridLayout.addWidget(self.txtAlgoAttribute, 2, 1, 1, 1)
        self.txtSkinName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtSkinName.setObjectName("txtSkinName")
        self.gridLayout.addWidget(self.txtSkinName, 1, 1, 1, 1)
        self.txtVersion = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtVersion.setText("")
        self.txtVersion.setObjectName("txtVersion")
        self.gridLayout.addWidget(self.txtVersion, 0, 3, 1, 1)
        self.lblCol = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblCol.setMaximumSize(QtCore.QSize(250, 20))
        self.lblCol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCol.setObjectName("lblCol")
        self.gridLayout.addWidget(self.lblCol, 1, 2, 1, 1)
        self.txtRow = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtRow.setObjectName("txtRow")
        self.gridLayout.addWidget(self.txtRow, 1, 3, 1, 1)
        self.lblRow = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblRow.setMaximumSize(QtCore.QSize(250, 20))
        self.lblRow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRow.setObjectName("lblRow")
        self.gridLayout.addWidget(self.lblRow, 2, 2, 1, 1)
        self.txtCol = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtCol.setObjectName("txtCol")
        self.gridLayout.addWidget(self.txtCol, 2, 3, 1, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.lblTableInfo = QtWidgets.QLabel(self.centralwidget)
        self.lblTableInfo.setGeometry(QtCore.QRect(20, 510, 211, 16))
        self.lblTableInfo.setObjectName("lblTableInfo")
        GenerateXAML.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(GenerateXAML)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1320, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuSettings.setFont(font)
        self.menuSettings.setObjectName("menuSettings")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuAbout.setFont(font)
        self.menuAbout.setObjectName("menuAbout")
        GenerateXAML.setMenuBar(self.menuBar)
        self.actionAbout = QtWidgets.QAction(GenerateXAML)
        self.actionAbout.setObjectName("actionAbout")
        self.actionGeneral = QtWidgets.QAction(GenerateXAML)
        self.actionGeneral.setObjectName("actionGeneral")
        self.menuSettings.addAction(self.actionGeneral)
        self.menuAbout.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(GenerateXAML)
        QtCore.QMetaObject.connectSlotsByName(GenerateXAML)
        GenerateXAML.setTabOrder(self.cmbSkins, self.txtSkinName)
        GenerateXAML.setTabOrder(self.txtSkinName, self.txtAlgoAttribute)
        GenerateXAML.setTabOrder(self.txtAlgoAttribute, self.txtHeader)
        GenerateXAML.setTabOrder(self.txtHeader, self.txtVersion)
        GenerateXAML.setTabOrder(self.txtVersion, self.txtRow)
        GenerateXAML.setTabOrder(self.txtRow, self.txtCol)
        GenerateXAML.setTabOrder(self.txtCol, self.tableWidget)
        GenerateXAML.setTabOrder(self.tableWidget, self.btnGenerate)
        GenerateXAML.setTabOrder(self.btnGenerate, self.btnExit)

    def retranslateUi(self, GenerateXAML):
        _translate = QtCore.QCoreApplication.translate
        GenerateXAML.setWindowTitle(_translate("GenerateXAML", "Skin Manager"))
        GenerateXAML.setToolTip(_translate("GenerateXAML", "Main window"))
        self.btnExit.setText(_translate("GenerateXAML", "Exit"))
        self.btnGenerate.setText(_translate("GenerateXAML", "Generate XAML!"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("GenerateXAML", "Row"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("GenerateXAML", "Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("GenerateXAML", "Datat Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("GenerateXAML", "Attributes"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("GenerateXAML", "Is Mandatory"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("GenerateXAML", "Minimum"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("GenerateXAML", "Maximum"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("GenerateXAML", "Increment"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("GenerateXAML", "Rounding"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("GenerateXAML", "Display Format"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("GenerateXAML", "Visibility"))
        self.lblSkin.setText(_translate("GenerateXAML", "Select Skin:"))
        self.label.setText(_translate("GenerateXAML", "Skin Version:"))
        self.lblHeader.setText(_translate("GenerateXAML", "Header Text:"))
        self.lblSkinName.setText(_translate("GenerateXAML", "Skin Name:"))
        self.txtHeader.setPlaceholderText(_translate("GenerateXAML", "Enter algo header text : [Hidden Algo Details]"))
        self.lblAlgoAttribute.setText(_translate("GenerateXAML", "Attribute Prefix:"))
        self.txtAlgoAttribute.setPlaceholderText(_translate("GenerateXAML", "Enter algo attribute prefix : [SA-Hermes-Hidden]"))
        self.txtSkinName.setPlaceholderText(_translate("GenerateXAML", "Enter Skin Name : [SA_Hermes_Hidden]"))
        self.txtVersion.setPlaceholderText(_translate("GenerateXAML", "Enter skin version"))
        self.lblCol.setText(_translate("GenerateXAML", "Number Of Rows:"))
        self.txtRow.setPlaceholderText(_translate("GenerateXAML", "Enter number of rows"))
        self.lblRow.setText(_translate("GenerateXAML", "Number Of Cols:"))
        self.txtCol.setPlaceholderText(_translate("GenerateXAML", "Enter number of columns"))
        self.lblTableInfo.setText(_translate("GenerateXAML", "* Double click on the row to remove"))
        self.menuSettings.setTitle(_translate("GenerateXAML", "Settings"))
        self.menuAbout.setTitle(_translate("GenerateXAML", "Help"))
        self.actionAbout.setText(_translate("GenerateXAML", "About"))
        self.actionGeneral.setText(_translate("GenerateXAML", "General"))

