
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GenerateXAML(object):
    def setupUi(self, GenerateXAML):
        GenerateXAML.setObjectName("GenerateXAML")
        GenerateXAML.resize(330, 350)
        GenerateXAML.setMaximumSize(QtCore.QSize(330, 350))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        GenerateXAML.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/appicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GenerateXAML.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(GenerateXAML)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSkin = QtWidgets.QLabel(self.centralwidget)
        self.lblSkin.setMaximumSize(QtCore.QSize(250, 20))
        self.lblSkin.setObjectName("lblSkin")
        self.gridLayout.addWidget(self.lblSkin, 7, 0, 1, 1)
        self.txtCol = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCol.setObjectName("txtCol")
        self.gridLayout.addWidget(self.txtCol, 20, 0, 1, 1)
        self.txtAlgoAttribute = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAlgoAttribute.setObjectName("txtAlgoAttribute")
        self.gridLayout.addWidget(self.txtAlgoAttribute, 6, 0, 1, 1)
        self.lblRow = QtWidgets.QLabel(self.centralwidget)
        self.lblRow.setMaximumSize(QtCore.QSize(250, 20))
        self.lblRow.setObjectName("lblRow")
        self.gridLayout.addWidget(self.lblRow, 19, 0, 1, 1)
        self.lblAlgoAttribute = QtWidgets.QLabel(self.centralwidget)
        self.lblAlgoAttribute.setMaximumSize(QtCore.QSize(250, 20))
        self.lblAlgoAttribute.setObjectName("lblAlgoAttribute")
        self.gridLayout.addWidget(self.lblAlgoAttribute, 4, 0, 1, 1)
        self.lblSkinName = QtWidgets.QLabel(self.centralwidget)
        self.lblSkinName.setMaximumSize(QtCore.QSize(250, 20))
        self.lblSkinName.setObjectName("lblSkinName")
        self.gridLayout.addWidget(self.lblSkinName, 1, 0, 1, 1)
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout.addWidget(self.btnExit, 22, 0, 1, 1)
        self.btnGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerate.setObjectName("btnGenerate")
        self.gridLayout.addWidget(self.btnGenerate, 21, 0, 1, 1)
        self.txtRow = QtWidgets.QLineEdit(self.centralwidget)
        self.txtRow.setObjectName("txtRow")
        self.gridLayout.addWidget(self.txtRow, 18, 0, 1, 1)
        self.txtSkinName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSkinName.setObjectName("txtSkinName")
        self.gridLayout.addWidget(self.txtSkinName, 3, 0, 1, 1)
        self.lblCol = QtWidgets.QLabel(self.centralwidget)
        self.lblCol.setMaximumSize(QtCore.QSize(250, 20))
        self.lblCol.setObjectName("lblCol")
        self.gridLayout.addWidget(self.lblCol, 11, 0, 1, 1)
        self.cmbSkins = QtWidgets.QComboBox(self.centralwidget)
        self.cmbSkins.setObjectName("cmbSkins")
        self.gridLayout.addWidget(self.cmbSkins, 10, 0, 1, 1)
        GenerateXAML.setCentralWidget(self.centralwidget)

        self.retranslateUi(GenerateXAML)
        QtCore.QMetaObject.connectSlotsByName(GenerateXAML)
        GenerateXAML.setTabOrder(self.txtSkinName, self.txtAlgoAttribute)
        GenerateXAML.setTabOrder(self.txtAlgoAttribute, self.cmbSkins)
        GenerateXAML.setTabOrder(self.cmbSkins, self.txtRow)
        GenerateXAML.setTabOrder(self.txtRow, self.txtCol)
        GenerateXAML.setTabOrder(self.txtCol, self.btnGenerate)
        GenerateXAML.setTabOrder(self.btnGenerate, self.btnExit)

    def retranslateUi(self, GenerateXAML):
        _translate = QtCore.QCoreApplication.translate
        GenerateXAML.setWindowTitle(_translate("GenerateXAML", "Skin Manager"))
        GenerateXAML.setToolTip(_translate("GenerateXAML", "Main window"))
        self.lblSkin.setText(_translate("GenerateXAML", "Select Skin:"))
        self.txtCol.setPlaceholderText(_translate("GenerateXAML", "Enter number of columns"))
        self.txtAlgoAttribute.setPlaceholderText(_translate("GenerateXAML", "Enter algo attribute name : [SA-Hermes-Hidden]"))
        self.lblRow.setText(_translate("GenerateXAML", "Number of columns:"))
        self.lblAlgoAttribute.setText(_translate("GenerateXAML", "Attribute Name:"))
        self.lblSkinName.setText(_translate("GenerateXAML", "Skin Name:"))
        self.btnExit.setText(_translate("GenerateXAML", "Exit"))
        self.btnGenerate.setText(_translate("GenerateXAML", "Generate XAML!"))
        self.txtRow.setPlaceholderText(_translate("GenerateXAML", "Enter number of rows"))
        self.txtSkinName.setPlaceholderText(_translate("GenerateXAML", "Enter Skin Name : [SA_Hermes_Hidden]"))
        self.lblCol.setText(_translate("GenerateXAML", "Number of rows:"))

